### ISSUE TITLE
Layout issue with the initialization interface

### ISSUE THREAD

**Issue by sunye-cn** [vuejs/create-vue#284]
When I create a new Vue project using Vite and run "npm run dev", a half-heart-shaped icon appears on the left side of the page in both Edge and Chrome browsers. After investigating, I found that this icon is related to the "Support Vue" option on the left side of the page and appears only when the page is zoomed out. Furthermore, the icon does not appear on the left side of the page when the page is zoomed in. I'm wondering if this is an intentional design or a bug.
![image](https://github.com/vuejs/create-vue/assets/79368159/7cd7a427-1000-46ff-941c-4be368c746ec)
![image](https://github.com/vuejs/create-vue/assets/79368159/2db6af02-00f5-41e6-9756-76017eb48125)

**Comment by henk-n** [comment]
I had the same issue and I fixed this with a minor change in the css

src/assets/base.css
```css
*::after {
  box-sizing: border-box;
  margin: 0;
  position: relative; <--- was missing
  font-weight: normal;
}

```
